# Generated by Django 5.0.6 on 2024-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='CMpassword',
            field=models.CharField(max_length=62),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=62),
        ),
    ]
