# Generated by Django 5.0.6 on 2024-05-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_show_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='networks',
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='tv_shows_app.network'),
        ),
    ]
